name: Terraform Plan, fmt,init, validate,tflint, trivy

on:
  push:
    branches: [main]
    paths:
      - 'infra/environment/dev/**'
      - 'infra/modules/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  security-events: write
  actions: read

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Linting, Scanning, Planning

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_APPLY_ARN }}
          aws-region: ${{ vars.AWS_REGION }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.2"

      - name: Terraform fmt
        working-directory: infra/
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=infra/environment/dev init

      - name: Terraform validate
        run: terraform -chdir=infra/environment/dev validate

      - name: setup tflint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.63.1

      - name: tflint install
        run: tflint --init

      - name: tflint scanning
        run:  tflint --recursive

      - name: Trivy IAC Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          scan-ref: infra/
          format: 'sarif'
          output: trivy-iac-results.sarif
          exit-code: '1'
          severity: CRITICAL,HIGH
          limit-severities-for-sarif: true

      - name: Upload Trivy IaC results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-iac-results.sarif

      - name: Publish Trivy IAC scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-iac-scan-${{ github.sha }}
          path: trivy-iac-results.sarif

      - name: Terraform plan
        run: terraform -chdir=infra/environment/dev force-unlock -force  513aa4dd-8ffc-551a-2ca1-4d839409a5a
        # run: terraform -chdir=infra/environment/dev plan -out=tfplan

      - name: Publish plan artefact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: infra/environment/dev/tfplan